// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ1oTo6gF-vB5YQ2j5NANthOjpleIt298',
    appId: '1:417817492250:web:4f7e60bad55cf2d397caa3',
    messagingSenderId: '417817492250',
    projectId: 'ecommerce-app-14449',
    authDomain: 'ecommerce-app-14449.firebaseapp.com',
    storageBucket: 'ecommerce-app-14449.appspot.com',
    measurementId: 'G-LK56F30GHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUYIDTlfT2giPjwGeXUMPcLLSm6D_osDE',
    appId: '1:417817492250:android:3ebc04da92a8d51f97caa3',
    messagingSenderId: '417817492250',
    projectId: 'ecommerce-app-14449',
    storageBucket: 'ecommerce-app-14449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPHyACSwugwZz5HN3nWy84dYPWLw0X0Gs',
    appId: '1:417817492250:ios:ca27bd7d930ebd3d97caa3',
    messagingSenderId: '417817492250',
    projectId: 'ecommerce-app-14449',
    storageBucket: 'ecommerce-app-14449.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPHyACSwugwZz5HN3nWy84dYPWLw0X0Gs',
    appId: '1:417817492250:ios:7136b88a6393c25697caa3',
    messagingSenderId: '417817492250',
    projectId: 'ecommerce-app-14449',
    storageBucket: 'ecommerce-app-14449.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
